pipeline {
  agent { 
    kubernetes {
      label 'kaniko-agent'
      defaultContainer 'kaniko'
      yaml """
apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: kaniko
spec:
  containers:
  - name: kaniko
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "2Gi"
        cpu: "1"
    image: gcr.io/kaniko-project/executor:debug
    imagePullPolicy: IfNotPresent
    command: ["sleep"]
    args: ["infinity"]
    volumeMounts:
    - name: dockerconfig
      mountPath: /kaniko/.docker
    env:
    - name: HOME
      value: "/home/jenkins/agent"
  restartPolicy: Never
  volumes:
  - name: dockerconfig
    projected:
      sources:
      - secret:
          name: dockerhubconfig
          items:
          - key: .dockerconfigjson
            path: config.json
"""
    }
  }

  environment {
    REGISTRY   = "docker.io"
    PROJECT    = "kimwooseop/ci_build"
    IMAGE = "${BUILD_TAG}"
  }

  stages {
    stage('Git Checkout') {
      steps {
        echo 'Github Repogitory Jenkinsfile & Sourcecode Checkout'
        checkout scm
      }
    }

    stage('Docker Image Build & Push') {
      steps {
        container(name: 'kaniko', shell: '/busybox/sh') {
          script {
            def dest = "${env.REGISTRY}/${env.PROJECT}:${env.IMAGE}"
            sh """
              echo "Image Building ${dest}"
              /kaniko/executor \
                --dockerfile=Dockerfile \
                --context=dir://./web \
                --destination=${dest} \
                --verbosity=debug \
                --cleanup
            """
          }
        }
      }
    }
  }

post {
  always {
    script {
      def dest = "${env.REGISTRY}/${env.PROJECT}:${env.IMAGE}"
      echo "Finished build of ${dest}"
    }
  }

  success {
    script {
      def image = "${env.REGISTRY}/${env.PROJECT}:${env.IMAGE}"

      build job: 'cd_auto',
        parameters: [
          string(name: 'IMAGE', value: image),
          string(name: 'GIT_BRANCH', value: 'main'),
          credentials(name: 'GIT_CREDENTIALS_ID', value: 'github-push-creds')
        ],
        wait: false
    }
  }
}
}